name: npm-build

# Only trigger on:
# - master branch
# - PR or Pull Request event types
# - Exclide Docusaurus files: this file, docs/** and website/**
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/docusaurus.yml'
      - 'docs/**'
      - 'website/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/docusaurus.yml'
      - 'docs/**'
      - 'website/**'
jobs:
  package-build:
    name: Build on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build